[build]
  # --- CAMBIO CLAVE AQUÍ ---
  # 'rm -rf flutter &&' BORRA la carpeta vieja de Flutter antes de descargar la nueva.
  # Esto asegura una instalación limpia en cada compilación.
  command = "rm -rf flutter && git clone -b stable https://github.com/flutter/flutter.git && ./flutter/bin/flutter build web --web-renderer html"

  # El directorio a publicar sigue siendo el mismo.
  publish = "build/web"