[build]
  # Este comando es más largo, pero garantiza que usemos una versión moderna de Flutter
  command = "git clone https://github.com/flutter/flutter.git && cd flutter && git checkout 3.19.0 && cd .. && ./flutter/bin/flutter build web --web-renderer html"

  # El directorio a publicar sigue siendo el mismo
  publish = "build/web"