[build]
  # --- CAMBIO CLAVE ---
  # 1. Borra la carpeta vieja (rm -rf)
  # 2. Descarga Flutter (git clone)
  # 3. Se asegura de estar en el canal estable (channel stable)
  # 4. ACTUALIZA a la última versión (upgrade)
  # 5. Construye la app
  command = "rm -rf flutter && git clone -b stable https://github.com/flutter/flutter.git && ./flutter/bin/flutter channel stable && ./flutter/bin/flutter upgrade && ./flutter/bin/flutter build web --web-renderer html"

  # El directorio a publicar sigue siendo el mismo
  publish = "build/web"